# -*- coding: utf-8 -*-
"""실제 테스트1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QbnhOxSK3UOzaoIgKg7AJajuIGbIcASb
"""

!pip install rlcard[torch]

import rlcard
from rlcard.agents import DQNAgent
from rlcard.agents import RandomAgent

env = rlcard.make("custom")
print("Number of actions:", env.num_actions)
print("Number of players:", env.num_players)
print("Shape of state:", env.state_shape)
print("Shape of action:", env.action_shape)

agent = DQNAgent(
    num_actions=env.num_actions,
    state_shape=env.state_shape[0],
    mlp_layers=[4096,4096],
)
agents = [agent]
for _ in range(1, env.num_players):
        agents.append(RandomAgent(num_actions=env.num_actions))

env.set_agents(agents)

from rlcard.utils import (
    tournament,
    reorganize,
    Logger,
    plot_curve,
)

with Logger("experiments/custom_dqn_result/") as logger:
    for episode in range(1000):

        # Generate data from the environment
        trajectories, payoffs = env.run(is_training=True)

        # Reorganaize the data to be state, action, reward, next_state, done
        trajectories = reorganize(trajectories, payoffs)

        # Feed transitions into agent memory, and train the agent
        for ts in trajectories[0]:
            agent.feed(ts)

        # Evaluate the performance.
        if episode % 50 == 0:
            logger.log_performance(
                env.timestep,
                tournament(
                    env,
                    10000,
                )[0]
            )

    # Get the paths
    csv_path, fig_path = logger.csv_path, logger.fig_path

plot_curve(csv_path, fig_path, "DQN")

"""You can find that the agent achieves an increasingly better performance with more training. All the logs and the model weights are saved in `experiments/leduc_holdem_dqn_result/`. Now you have your trained DQN agent on Blackjack!"""